server:
  port: 9001

spring:
  application:
    name: program-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/program_base?characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true

jwt:
  config:
    key: xszx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka

  instance:
    prefer-ip-address: true
