server:
  port: 9008

spring:
  application:
    name: program-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.106:3306/program_user?characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true

  redis:
    host: 192.168.1.106
    port: 6379

  rabbitmq:
    host: 192.168.1.106

jwt:
  config:
    key: xszx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka

  instance:
    prefer-ip-address: true
